autocorrelation = sm.tsa.pacf(y)
plt.stem(autocorrelation)
plt.axhline(y=0.0, color='black', linestyle='-')
plt.axhline(y=1.96*n**-0.5, color='red', linestyle='--')
plt.axhline(y=-1.96*n**-0.5, color='red', linestyle='--')
plt.xlabel('Lag') 
plt.ylabel('PACF coefficient')
plt.title('PACF Plot')
plt.show()
