plt.figure(figsize=(15,10))
plt.scatter(x, y, label="data")
plt.plot(x, X@betastar, c="orange", label="model")
plt.grid(True)
plt.xlabel("x", fontsize=22) 
plt.ylabel("y", fontsize=22)
plt.legend(fontsize=22)
plt.title("Plot of y against x", fontsize=22)
plt.show()
