plt.figure(figsize=(15,10))
plt.plot(np.arange(n), y)
plt.xlabel('Months since 2004') 
plt.ylabel('Interest in "Playoffs" (United States)')
plt.title('Interest in "Playoffs" (United States) since 2004')
plt.show()
